# Generated by Django 4.2.7 on 2023-11-01 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_post_post_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["posted_at"]},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="post_date",
            new_name="posted_at",
        ),
    ]
