# Generated by Django 4.2.7 on 2023-11-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_post_options_rename_post_date_post_posted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_abc",
            field=models.BooleanField(default=False),
        ),
    ]
